workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - flutter pub get
      - cd ios && pod install
      - flutter build ios --simulator --no-codesign
      - |
        mkdir -p build/ios/simulator
        cd build/ios/iphonesimulator
        mkdir -p Payload
        cp -r Runner.app Payload/
        zip -r ../simulator/Runner.zip Payload/
    artifacts:
      - build/ios/simulator/*.zip
